name: MineteryaRPG
main: com.bricou.mineteryarpg.MineteryaRPG
version: 0.1

commands:
    rpgaide:
        description: Affiche l'aide
        usage: usage /rpgaide
    rpgclasse:
        description: Selection d'une classe
        usage: usage /classe <nom de la classe>