name: MineteryaRPG
main: com.bricou.mineteryarpg.MineteryaRPG
version: 0.1

commands:
    rpgaide:
        description: Affiche l'aide
        usage: /rpgaide
    rpgclasse:
        description: Selection d'une classe
        usage: /rpgclasse <nom de la classe>
    rpgstats:
        description: Donne les informations d'un joueur
        usage: /rpgstats [joueur]
    rpghash:
        description: toto
        usage: toto